services:
  # === Backend (Node.js API) ===
  - type: web
    name: hunter-forum
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 22.16.0

  # === Frontend (Static Site) ===
  - type: web
    name: hunter-forum-static
    env: static
    buildCommand: ""             # No build needed for pure HTML/CSS/JS
    staticPublishPath: ./public  # Serves content in public/
