# === Backend (Node.js API) ===
services:
  - type: web
    name: hunter-forum
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    webSockets: true
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: JWT_SECRET
        value: "your_jwt_secret_here"  # Replace with a strong secret
      - key: DATABASE_URL
        value: "your_database_connection_string_here" # Replace with Render Postgres DB URL

# === Frontend (Static Site) ===
staticSites:
  - name: hunter-forum-static
    plan: free
    buildCommand: ""          # No build needed for plain HTML/CSS/JS
    publishPath: public       # Ensure your HTML/CSS/JS files are inside 'public'
    envVars:
      - key: API_URL
        value: "https://hunter-forum.onrender.com"  # Link to your backend
